# Generated by Django 4.2.3 on 2024-01-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='tickets_available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
