# Generated by Django 4.2.3 on 2024-01-13 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Festival',
        ),
    ]
