# Generated by Django 4.2.3 on 2024-01-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='cost',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='features',
            field=models.TextField(default='fun'),
            preserve_default=False,
        ),
    ]
