# Generated by Django 4.2.3 on 2024-01-14 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_ticket_cost_ticket_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('anonymous', models.BooleanField()),
                ('supporter', models.CharField(max_length=200)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.festival')),
                ('ticket_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.ticket')),
            ],
        ),
    ]
