# Generated by Django 4.2.3 on 2024-01-19 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_pledge_supporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='festival',
        ),
    ]
