# Generated by Django 4.2.3 on 2024-01-16 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_pledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_name',
            field=models.CharField(default='test ticket', max_length=200),
            preserve_default=False,
        ),
    ]
