# Generated by Django 4.2.3 on 2024-01-19 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_ticket_festival'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='festival',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='projects.festival'),
            preserve_default=False,
        ),
    ]
