# Generated by Django 4.2.3 on 2024-03-12 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_festival_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='pledge_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
