# Generated by Django 4.2.3 on 2024-03-13 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_pledge_pledge_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='ticket_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='projects.ticket'),
        ),
    ]
